name: Update repository labels

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/labels.yml'

jobs:
  create-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      LABELS_JSON: |
        [
          {"name": "research", "color": "ededed", "description": "Research needed"},
          {"name": "ops", "color": "c2e0c6", "description": "Ops task"},
          {"name": "ci", "color": "bfdadc", "description": "Related to GitHub Actions CI"}
        ]
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const labels = JSON.parse(process.env.LABELS_JSON);
          for (const label of labels) {
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name,
              description: label.description,
              color: label.color
            });
          }
