name: Update repository labels

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/labels.yml'

permissions:
  actions: write

jobs:
  create-labels:
    runs-on: ubuntu-latest
    env:
      LABELS_JSON: |
        [
          {"name": "research", "color": "ededed"},
          {"name": "ops", "color": "c2e0c6"},
          {"name": "ci", "color": "bfdadc"}
        ]
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const labels = JSON.parse(process.env.LABELS_JSON);
          for (const label of labels) {
            github.rest.issues.createLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name,
              color: label.color
            });
          }
